Minimal models for remote
SeldonIO/tempo pull request #77
Opened 2021-04-01 19:19 UTC by RafalSkolasinski

Fixes https://github.com/SeldonIO/tempo/issues/54

2021-04-02 10:13 UTC, cliveseldon requested changes

2021-04-02 10:13 UTC, cliveseldon commented on docs/examples/intro/local.md
>  ```python
* Wrong location for conda.yaml
 * Also I changed to use file syntax for consistency and clarity
 * wrong version of mlserver

```
%%writetemplate artifacts/classifier/conda.yaml
name: tempo
channels:
  - defaults
dependencies:
  - python=3.7
  - pip:
    - mlops-tempo @ file://{TEMPO_DIR}
    - mlserver==0.3.1.dev7
 ```

Also not need to remove this file from github and add to .gitignore as its generated.

2021-04-02 10:13 UTC, cliveseldon commented on docs/examples/intro/k8s.md
> -%%writefile artifacts/classifier/conda.yaml
Same changes needed here as in local.ipynb

2021-04-02 10:13 UTC, cliveseldon commented on docs/examples/intro/local-class.ipynb
> +{
Needs same changes as other notebooks,

2021-04-07 16:06 UTC, RafalSkolasinski commented
Fixed notebooks:
- intro
- explainers
- outlier (removed alibi dependency as in fixme note read)

Added:
- control environment (notebooks that trains and deploy Iris sklearn / xgboost as mlserver from a controlled environment)

2021-04-07 16:41 UTC, merged